Keras toolkit#8 use python toolkit
BHoM/TensorFlow_Toolkit pull request #14
Opened 2019-12-19 11:14 UTC by epignatelli

### NOTE: Depends on 
Despite the code itself does not have dependency, this pr is coupled with https://github.com/BHoM/Numpy_Toolkit/pull/9.
It will compile if you're not on that branch, but the toolkit will not work.

   
### Issues addressed by this PR

Closes #6

### Test files

This requires a bit of a clean up to avoid conflicts. 
1. Remove the `BHoM/Assemblies` folder
2. Compile the Python_Toolkit
3. Compile the Numpy_Toolkit
4. Compile the Keras_Toolkit
4. Use any test script from the Numpy of Keras library, e.g. https://burohappold.sharepoint.com/:f:/s/BHoM/Ei4hzzyRJqNPpqF_CHW4EmIBLrFsCtg33CEeYRZdTIvh4A?e=j7Gljx

### Changelog

### Additional comments

2020-01-31 15:39 UTC, epignatelli commented
CTRL C + CTRL V
@alelom @FraserGreenroyd all ready for review! Let me know if you need help with that!

2020-02-03 09:18 UTC, FraserGreenroyd requested changes
I could not get this to work in the way described in the PR body, I could not get Python installer using the dependent toolkits, nor test Keras_Engine itself I'm afraid. See some comments on the code - might be worth going through this together at some point @epignatelli ?

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras/Keras.csproj
> +      <HintPath>..\..\Python_Toolkit\Build\Python.Runtime.dll</HintPath>
Copy local should be set to false

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras/Keras.csproj
>        <HintPath>..\..\Numpy_Toolkit\Build\Numpy.dll</HintPath>
Copy local should be set to false

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras/Keras.csproj
> +      <HintPath>..\..\Python_Toolkit\Build\Python_Engine.dll</HintPath>
Copy local should be set to false

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras_Engine/Keras_Engine.csproj
> +      <HintPath>..\..\Python_Toolkit\Build\Python.Runtime.dll</HintPath>
Copy local should be set to false

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras_Engine/Keras_Engine.csproj
> +      <HintPath>..\..\Python_Toolkit\Build\Python_Engine.dll</HintPath>
Copy local should be set to false

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras_Engine/Keras_Engine.csproj
> +$(SolutionDir)/../Python_Toolkit/Python_PostBuild/bin/Debug/Python_Postbuild.exe "pillow" "tensorflow==2.0"</PostBuildEvent>
This wasn't working for me - but if I removed `Installing keras in python at compile time` then it did. With that in, it had a 9009 error, but removing that would make it build (but Python did not install - more on that in Python_Toolkit).

2020-02-03 09:18 UTC, FraserGreenroyd commented on Keras_Engine/Query/Load.cs
> + * Copyright (c) 2015 - 2019, the respective contributors. All rights reserved.
Copyright now needs to be to 2020

2020-02-13 11:46 UTC, FraserGreenroyd approved these changes
Have re run the steps in the PR body and am happy this is now working following the changes @epignatelli

2020-02-13 11:50 UTC, epignatelli commented
Thanks @FraserGreenroyd!

@alelom since this will be pretty foundational, would you mind trying this as well?

We should really have something that reflects the comments when solving PRs that span across different repos, but are actually the same 😄

2020-02-13 11:58 UTC, FraserGreenroyd commented
> We should really have something that reflects the comments when solving PRs that span across different repos, but are actually the same 😄

🤣 agreed! I almost wore out my Ctrl C + V buttons on these PRs!

2020-02-13 11:59 UTC, epignatelli commented
We might have the bot listening to the comments that happen on prs with a specific tag, like
`Liked to: X/pulls/Y`?

2020-02-14 08:19 UTC, epignatelli commented
https://github.com/BHoM/Numpy_Toolkit/pull/12#issuecomment-586148394

2020-02-14 08:19 UTC, merged

2020-02-14 10:54 UTC, alelom commented
Adding to approvals as requested ![image](https://user-images.githubusercontent.com/6352844/74525155-5e697380-4f18-11ea-8beb-bdc968d94604.png)

2020-02-14 10:55 UTC, epignatelli commented
Lovely, thanks @alelom !!